name = "OpenFST"
uuid = "18031d04-943d-420a-99da-58315a5a21aa"
authors = ["Laurent Bartholdi <laurent.bartholdi@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
